module.exports = (function () {
  
  return {
    0: "Job",
    1: "Doc",
    2: "Borough",
    3: "House",
    4: "StreetName",
    5: "Block",
    6: "Lot",
    7: "Bin",
    8: "JobType",
    9: "JobStatus",
    10: "JobStatusDescrp",
    11: "LatestActionDate",
    12: "BuildingType",
    13: "CommunityBoard",
    14: "Cluster",
    15: "Landmarked",
    16: "AdultEstab",
    17: "LoftBoard",
    18: "CityOwned",
    19: "Littlee",
    20: "PCFiled",
    21: "eFilingFiled",
    22: "Plumbing",
    23: "Mechanical",
    24: "Boiler",
    25: "FuelBurning",
    26: "FuelStorage",
    27: "Standpipe",
    28: "Sprinkler",
    29: "FireAlarm",
    30: "Equipment",
    31: "FireSuppression",
    32: "CurbCut",
    33: "Other",
    34: "OtherDescription",
    35: "ApplicantName",
    36: "ApplicantProfessionalTitle",
    37: "ApplicantLicense",
    38: "ProfessionalCert",
    39: "PreFilingDate",
    40: "Paid",
    41: "FullyPaid",
    42: "Assigned",
    43: "Approved",
    44: "FullyPermitted",
    45: "InitialCost",
    46: "TotalEstFee",
    47: "FeeStatus",
    48: "ExistingZoningSqft",
    49: "ProposedZoningSqft",
    50: "HorizontalEnlrgmt",
    51: "VerticalEnlrgmt",
    52: "EnlargementSQFootage",
    53: "StreetFrontage",
    54: "ExistingNoofStories",
    55: "ProposedNoofStories",
    56: "ExistingHeight",
    57: "ProposedHeight",
    58: "ExistingDwellingUnits",
    59: "ProposedDwellingUnits",
    60: "ExistingOccupancy",
    61: "ProposedOccupancy",
    62: "SiteFill",
    63: "ZoningDist1",
    64: "ZoningDist2",
    65: "ZoningDist3",
    66: "SpecialDistrict 1",
    67: "SpecialDistrict 2",
    68: "OwnerType",
    69: "NonProfit",
    70: "OwnerName",
    71: "OwnerBusinessName ",
    72: "OwnerHouseStreet",
    73: "CityStateZip",
    74: "OwnerPhone",
    75: "JobDescription"
  }

})()  