module.exports = (function () {
  
    var lookup2015 = {
      0: "Borough"
      1: "Bin"
      2: "House"
      3: "StreetName"
      4: "Job"
      5: "Jobdoc"
      6: "JobType"
      7: "SelfCert"
      8: "Block"
      9: "Lot"
      10: "CommunityBoard"
      11: "ZipCode"
      12: "BldgType"
      13: "Residential"
      14: "SpecialDistrict1"
      15: "SpecialDistrict2"
      16: "WorkType"
      17: "PermitStatus"
      18: "FilingStatus"
      19: "PermitType"
      20: "PermitSequence"
      21: "PermitSubtype"
      22: "OilGas"
      23: "SiteFill"
      24: "FilingDate"
      25: "IssuanceDate"
      26: "ExpirationDate"
      27: "JobStartDate"
      28: "PermitteesName"
      29: "PermitteesBusinessName"
      30: "PermitteesPhone"
      31: "PermitteesLicenseType"
      32: "PermitteesLicense"
      33: "PermitteesOtherTitle"
      34: "ActsAsSuperintendent"
      35: "HICLicense"
      36: "SiteSafetyMgrsName"
      37: "SiteSafetyMgrBusinessName"
      38: "SuperintendentName"
      39: "SuperintendentBusinessName"
      40: "OwnersBusinessType"
      41: "NonProfit"
      42: "OwnersBusinessName"
      43: "OwnersName"
      44: "OwnersHouseStreet"
      45: "OwnersCityStateZip"
      46: "OwnersPhone"
    }

    return lookup2015;

})()